---
# control
control:
  data_name: SmartHome-hh105~2015~2016~2017
  model_name: base
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
resume_mode: 0
profile: False
